version: '3.1'

services:
  ghost:
    image: ghost:3-alpine
    ports:
      - 3001:2368
    environment:
      url: http://localhost:3001
    volumes:
      # Redirects and database data
      - .ghost/data:/var/lib/ghost/content/data
      # Uploaded images
      - .ghost/images:/var/lib/ghost/content/images
